### ISSUE TITLE
Create Deck Class

### ISSUE THREAD

**Issue by highspirit7** [highspirit7/war_card_game#4]
Reference : https://pourmavie.notion.site/Necessary-Classes-OOP-7399cfe8ed75483ca71e6b0820b60dcd?pvs=4

**Comment by barturas** [comment]
created a branch 'deck-class' and commited deck.py

**Comment by highspirit7** [comment]
created 'deck-class-jiyeol' branch from 'deck-class' branch and modifed deck.py and merge it to main branch.
